sudo: required
services:
  - docker

before_install:
  - docker build -t hoangnguyendn/docker-react -f Dockerfile.dev .

script:
  - docker run hoangnguyendn/docker-react

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-651541711457"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $aws_id
  secret_access_key:
    secure: "$aws"